import "./globals.css";
import { Header } from "@/components/Header";
import { AuthProvider } from "@/components/AuthProvider";
import { getCategories } from "@/lib/catalog";
import type { Metadata, Viewport } from "next";
import { SITE_NAME, SITE_DESCRIPTION, SITE_URL, DEFAULT_OG_IMAGE } from "@/lib/seo";
import { SeoJsonLd } from "@/components/SeoJsonLd";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_NAME,
    template: `${SITE_NAME} | %s `,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  category: "firearms, guns, rocket-launchers, drugs, credit cards,resident cards",
  keywords: [
    "le monde parallel",
    "Le Monde Parallel",
    "LMP: Le Monde Parallel",
    "lmp: le monde parallel",
    "gun dealers in europe",
    "gun dealers in germany",
    "gun dealers in france",
    "drugs in europe",
    "buy drugs",
    "rocket launchers",
    "buy rocket launchers",
    "buy glock",
    "les arms a feu",
    "un pistolet",
    "un fusil",
    "arms a guerre",
    "armoire",
    "Armory 2.0",
    "Armoire ",
    "narco subs",
    "submarine",
    "narco pilots",
    "pilote de avion",
    "les avions",
    "cartel market",
    "les arms",
    "le glock",
    "le beretta",
    "kalash ",
    "ak47",
    "AK-47",
    "Kalashnikov",
    "carding",
    "carte preapaye",
    "carte noir",
    "carte blanch",
    "carte visa",
    "carte a gratte",
    "armory",
    "armoire 2.0",
    "armurerie",
    "arm a main",
    "fire arms for sale",
    "best firm arms store",
    "trusted firearms store",
    "100% trusted gun vendor",
    "marche de arms a feu",
    "marche de arms",
    "euro guns",
    "euro guns store",
    "euroguns",
    "Guns",
    "weapons",
    "weapons in europe",
    "euro-guns",
    "delivery in europe",
    "fast delivery in europe",
    "fast delivery",
    "gunstore of europe",
    "frenchguns",
    "french guns store",
    "french Guns",
    "underground armory",
    "pistolen",
    "Schrotflinten",
    "Sturmgewehr",
    "deutscher market",
    "Bestätigter Waffenverkäufer",
    "guns",
    "gear",
    "ammo",
    "ammunition",
    "optics",
    "sniper",
    "hitman",
    "untraceable guns",
    "unregistered guns",
    "Ghost guns",
    "Thriving gun shop",
    "The 2nd amendment store",
    "revolvers",
    "rifles",
    "shotguns",
    "automatic rifles",
    "rocket launchers",
    "drug lords",
    "private planes",
    "small planes",
    "narco flights",
    "narco submarines",
    "fast delivery",
    "pan europe guns",
    "pan america guns",
    "american guns",
    "european arms",
    "anony guns",
    "underground guns",
    "underground market",
    "gunmarket",
    "germanguns",
    "german guns",
    "italian guns",
    "spanish guns",
    "UK GUNS",
    "uk guns and ammo",
    "euroguns and ammo",
    "guns and ammo",
    "ammo and guns",
    "underground gun market",
    "Beste deutsche",
    "phantom firearms",
    "unserialized guns",
    "best deep web gun store",
    "best dark web gun store",
    "best gunshop",
    "trusted gunshop",
    "trusted gun store",
    "guns for bitcoin",
    "buy guns for bitcoin",
    "buy weapons for bitcoin",
    "guns bitcoin",
    "ghost guns for bitcoin",
    "united guns",
    "guns market",
    "top black market",
    "tor black market",
    "darkweb market",
    "utopia marketplace",
    "marketplace",
    "tor mart",
    "german arms",
    "firearms 72",
    "firearms 1",
    "arme de poing",
    "arme de poigne",
    "arme long",
    "munition",
    "cartouche",
    "Vendeur d'armes professionnel",
    "vendeur d'armes",
    "dealer d'armes",
    "dealer",
    "coke en stock",
    "french world",
    "french world ancienne",
    "shop french",
    "francais",
    "francaise",
    "arme a feu a poigne",
    "carte d'identite ",
    "titre de sejour",
    "titre de voyage",
    "passport",
    "titre de refugie",
    "carte de resident",
    "permis de conduire",
    "carte gris",
    "des impots",
    "avis de impots",
    "assurence auto",
    "numero d'immmatriculation",
    "passport francais",
    "permis de porte de arme",
    "cocaina",
    "coke",
    "tabac",
    "paris fixe",
    "paris sur",
    "des arms a feu",
    "glock",
    "glock 17",
    "glock 19",
    "glock 23",
    "papiers",
    "carte bancaire visa prepaye",
    "euroepean driving licence",
    "french driving licence",
    "permis de conduire",
    "permis de conduire A",
    "permis de conduire B",
    "porte de armes",
    "cassier judicaire",
    "CAF",
    "pole emploi",
    "caisse maladie",
    "la paname",
    "ile de france",
    "police national",
    "police municipale",
    "gendarmerie",
    "carte maladie",
    "papiers german",
    "papiers francais",
    "papiers italien",
    "papiers portugais",
    "permis de conduire allemand",
    "carte vole",
    "carte escro",
    "le espionage prive",
    "rpg-30",
    "IGLA 9K38",
    "JAVELIN FGM148",
    "NLAW ANTI TANK",
    "BERNARD PRAKTIKAL",
    "SMITH AND WESSON 5906",
    "SIG P211",
    "CZ75 SE",
    "CZ P-10",
    "MAGNUM MARK XIX",
    "SPRING FIELD 1911",
    "BETERRA 92FS",
    "GLOCK 17 5TH GENERATION",
    "AMERICAN ARMS",
    "MUNITION CERTIFIE",
    "92 STINGER",
    "CARTE DEUX MILLE BALL",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: "/",
    siteName: SITE_NAME,
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    images: [
      {
        url: DEFAULT_OG_IMAGE,
        width: 1920,
        height: 1080,
        alt: `${SITE_NAME} : Le Monde Parallel`,
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: DEFAULT_OG_IMAGE,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};


export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const categories = await getCategories();

  return (
    <html lang="en">
      <body>
        <SeoJsonLd
          data={{
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "Organization",
                "@id": `${SITE_URL}/#organization`,
                name: SITE_NAME,
                url: SITE_URL,
                logo: `${SITE_URL}${DEFAULT_OG_IMAGE}`,
              },
              {
                "@type": "WebSite",
                "@id": `${SITE_URL}/#website`,
                url: SITE_URL,
                name: SITE_NAME,
                description: SITE_DESCRIPTION,
                publisher: {
                  "@id": `${SITE_URL}/#organization`,
                },
              },
            ],
          }}
        />
        <AuthProvider>
          <div className="site">
            <div className="top-space" />
            <Header categories={categories} />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
