export const LANGUAGE_STORAGE_KEY = "lonely-road-language";
export const languages = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱" },
  { code: "fi", label: "Suomi", flag: "🇫🇮" },
  { code: "no", label: "Norsk", flag: "🇳🇴" },
  { code: "pl", label: "Polski", flag: "🇵🇱" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "hr", label: "Hrvatski", flag: "🇭🇷" },
] as const;
export const DEFAULT_LANGUAGE = "en";

export type LanguageCode = (typeof languages)[number]["code"];

export function isLanguageCode(value: string): value is LanguageCode {
  return languages.some((language) => language.code === value);
}

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    categories: "CATEGORIES", language: "LANGUAGE", login: "LOG IN", register: "REGISTER",
    loadingAuthentication: "Loading authentication…", topUpDeposit: "TOP UP / DEPOSIT", purchaseItem: "PURCHASE ITEM", confirmOrder: "CONFIRM ORDER", unitSalePrice: "Unit sale price", quantity: "Quantity", decreaseQuantity: "Decrease quantity", increaseQuantity: "Increase quantity", orderTotal: "Order total", escrow: "Escrow", safeDeal: "Safe Deal", safeDealDescription: "With Safe Deal you first receive the product, then after checking it you release the payment to the seller.", total: "Total", delivery: "Delivery", deliveryMethod: "Delivery method:", mailDelivery: "Mail delivery", parcelLocker: "Parcel locker", pgpWarning: "You have no PGP key. Tracking number will not be encrypted.", addEncryptionKey: "Add encryption key", shippingAddress: "Shipping Address", addressLabel: "Address Label (optional)", addressLabelPlaceholder: "Home, Work, etc.", recipientName: "Recipient Name *", fullName: "Full name", countryRequired: "Country *", countryPlaceholder: "Country", regionStateOptional: "Region/State (optional)", regionStatePlaceholder: "Region or State", cityRequired: "City *", cityPlaceholder: "City", postalCodeRequired: "Postal Code *", postalCodeOptional: "Postal Code (optional)", postalCodePlaceholder: "Postal/ZIP code", addressLine1Required: "Address Line 1 * (Street, house number)", streetAddressPlaceholder: "Street address", addressLine2Optional: "Address Line 2 (Apartment, suite, unit)", apartmentPlaceholder: "Apartment, floor, etc.", selectCountry: "- Select Country -", selectCountryFirst: "- Select country first -", lockerNetworkRequired: "Parcel locker network *", selectLockerNetwork: "- Select parcel locker network -", lockerIdRequired: "Parcel locker ID * (Point code from the carrier website)", lockerIdPlaceholder: "For example: KRA010, 4711-Berlin", lockerAddressOptional: "Parcel locker address (optional)", saveLocker: "Save this parcel locker for future orders", lockerSellerNotice: "The seller will be notified that the parcel must be sent to a parcel locker.", commentToOrder: "Comment to order", orderCommentPlaceholder: "Optional message for the seller", warning: "Warning:", purchaseWarning: "By clicking buy, your money will be transferred to the seller and you will not be able to cancel the purchase. You must trust the seller to complete this transaction. If you do not trust the seller, use escrow purchase.", yourPin: "Your Pin", insufficientBalance: "You do not have enough money to buy this product.", buy: "BUY",

    purchases: "MY PURCHASES", messages: "MESSAGES", help: "HELP", balance: "BALANCE", logout: "LOG OUT",
    quickSearch: "⌕ QUICK SEARCH", searchByName: "Search by name:", searchPlaceholder: "What are you looking for?",
    location: "Location:", selectLocation: "Select location", category: "Category:", selectCategory: "Select category",
    priceRange: "Price range:", from: "from", to: "to", search: "Search", latestReviews: "LATEST REVIEWS",
    newCatalogs: "NEW CATALOGS", shops: "★  SHOPS", home: "Home", verified: "✓ Verified", deals: "Deals",
    vendorLevel: "Vendor Lvl", rating: "Rating", viewShop: "View Shop", noResults: "No catalogue items match your search.",
    demoCredit: "1 DEMO CREDIT = $1.00", loginTitle: "Login", loginSubtitle: "Please login to access the catalogue.",
    usernameOrEmail: "USERNAME OR EMAIL", usernameEmailPlaceholder: "Your username or email", password: "PASSWORD",
    loginButton: "Login", loggingIn: "Logging in…", noAccount: "If you do not have an account,", registerLink: "register",
    registerTitle: "Register", registerSubtitle: "Create an account for the catalogue demo.", displayName: "DISPLAY NAME",
    yourDisplayName: "Your display name", username: "USERNAME", usernamePlaceholder: "3-32 characters", email: "EMAIL",
    passwordPlaceholder: "At least 8 characters", repeatPassword: "REPEAT PASSWORD", repeatPlaceholder: "Repeat password",
    creatingAccount: "Creating account…", alreadyAccount: "Already have an account?", loginLink: "login",
  },
  nl: {
    categories: "CATEGORIEËN", language: "TAAL", login: "INLOGGEN", register: "REGISTREREN", purchases: "MIJN AANKOPEN", messages: "BERICHTEN", help: "HULP", balance: "SALDO", logout: "UITLOGGEN",
    quickSearch: "⌕ SNEL ZOEKEN", searchByName: "Zoeken op naam:", searchPlaceholder: "Waar ben je naar op zoek?", location: "Locatie:", selectLocation: "Selecteer locatie", category: "Categorie:", selectCategory: "Selecteer categorie", priceRange: "Prijsbereik:", from: "vanaf", to: "tot", search: "Zoeken", latestReviews: "LAATSTE REVIEWS", newCatalogs: "NIEUWE CATALOGI", shops: "★  WINKELS", home: "Home", verified: "✓ Geverifieerd", deals: "Deals", vendorLevel: "Leveranciersniveau", rating: "Beoordeling", viewShop: "Bekijk winkel", noResults: "Geen catalogusitems komen overeen met je zoekopdracht.", demoCredit: "1 DEMOKREDIET = $1,00", loginTitle: "Inloggen", loginSubtitle: "Log in om de catalogus te bekijken.", usernameOrEmail: "GEBRUIKERSNAAM OF E-MAIL", usernameEmailPlaceholder: "Je gebruikersnaam of e-mail", password: "WACHTWOORD", loginButton: "Inloggen", loggingIn: "Inloggen…", noAccount: "Heb je nog geen account?", registerLink: "registreren", registerTitle: "Registreren", registerSubtitle: "Maak een account voor de catalogusdemo.", displayName: "WEERGAVENAAM", yourDisplayName: "Je weergavenaam", username: "GEBRUIKERSNAAM", usernamePlaceholder: "3-32 tekens", email: "E-MAIL", passwordPlaceholder: "Minimaal 8 tekens", repeatPassword: "WACHTWOORD HERHALEN", repeatPlaceholder: "Herhaal wachtwoord", creatingAccount: "Account aanmaken…", alreadyAccount: "Heb je al een account?", loginLink: "inloggen",
  },
  fi: {
    categories: "KATEGORIAT", language: "KIELI", login: "KIRJAUDU", register: "REKISTERÖIDY", purchases: "OSTOKSENI", messages: "VIESTIT", help: "OHJE", balance: "SALDO", logout: "KIRJAUDU ULOS",
    quickSearch: "⌕ PIKAHaku", searchByName: "Hae nimellä:", searchPlaceholder: "Mitä etsit?", location: "Sijainti:", selectLocation: "Valitse sijainti", category: "Kategoria:", selectCategory: "Valitse kategoria", priceRange: "Hintaluokka:", from: "alkaen", to: "asti", search: "Hae", latestReviews: "VIIMEISIMMÄT ARVOSTELUT", newCatalogs: "UUDET LUETTELOT", shops: "★  KAUPAT", home: "Koti", verified: "✓ Vahvistettu", deals: "Tarjoukset", vendorLevel: "Myyjätaso", rating: "Arvio", viewShop: "Näytä kauppa", noResults: "Hakusi ei tuottanut tuloksia.", demoCredit: "1 DEMOHYVITYS = $1,00", loginTitle: "Kirjaudu", loginSubtitle: "Kirjaudu nähdäksesi luettelon.", usernameOrEmail: "KÄYTTÄJÄNIMI TAI SÄHKÖPOSTI", usernameEmailPlaceholder: "Käyttäjänimesi tai sähköpostisi", password: "SALASANA", loginButton: "Kirjaudu", loggingIn: "Kirjaudutaan…", noAccount: "Eikö sinulla ole tiliä?", registerLink: "rekisteröidy", registerTitle: "Rekisteröidy", registerSubtitle: "Luo tili luettelodemoa varten.", displayName: "NÄYTTÖNIMI", yourDisplayName: "Näyttönimesi", username: "KÄYTTÄJÄNIMI", usernamePlaceholder: "3–32 merkkiä", email: "SÄHKÖPOSTI", passwordPlaceholder: "Vähintään 8 merkkiä", repeatPassword: "TOISTA SALASANA", repeatPlaceholder: "Toista salasana", creatingAccount: "Luodaan tiliä…", alreadyAccount: "Onko sinulla jo tili?", loginLink: "kirjaudu",
  },
  no: {
    categories: "KATEGORIER", language: "SPRÅK", login: "LOGG INN", register: "REGISTRER", purchases: "MINE KJØP", messages: "MELDINGER", help: "HJELP", balance: "SALDO", logout: "LOGG UT",
    quickSearch: "⌕ HURTIGSØK", searchByName: "Søk etter navn:", searchPlaceholder: "Hva leter du etter?", location: "Sted:", selectLocation: "Velg sted", category: "Kategori:", selectCategory: "Velg kategori", priceRange: "Prisintervall:", from: "fra", to: "til", search: "Søk", latestReviews: "SISTE ANMELDELSER", newCatalogs: "NYE KATALOGER", shops: "★  BUTIKKER", home: "Hjem", verified: "✓ Verifisert", deals: "Tilbud", vendorLevel: "Selgernivå", rating: "Vurdering", viewShop: "Se butikk", noResults: "Ingen katalogvarer samsvarer med søket.", demoCredit: "1 DEMOKREDITT = $1,00", loginTitle: "Logg inn", loginSubtitle: "Logg inn for å få tilgang til katalogen.", usernameOrEmail: "BRUKERNAVN ELLER E-POST", usernameEmailPlaceholder: "Brukernavn eller e-post", password: "PASSORD", loginButton: "Logg inn", loggingIn: "Logger inn…", noAccount: "Har du ikke en konto?", registerLink: "registrer", registerTitle: "Registrer", registerSubtitle: "Opprett en konto for katalogdemoen.", displayName: "VISNINGSNAVN", yourDisplayName: "Visningsnavnet ditt", username: "BRUKERNAVN", usernamePlaceholder: "3–32 tegn", email: "E-POST", passwordPlaceholder: "Minst 8 tegn", repeatPassword: "GJENTA PASSORD", repeatPlaceholder: "Gjenta passord", creatingAccount: "Oppretter konto…", alreadyAccount: "Har du allerede en konto?", loginLink: "logg inn",
  },
  pl: {
    categories: "KATEGORIE", language: "JĘZYK", login: "ZALOGUJ SIĘ", register: "REJESTRACJA", purchases: "MOJE ZAKUPY", messages: "WIADOMOŚCI", help: "POMOC", balance: "SALDO", logout: "WYLOGUJ SIĘ",
    quickSearch: "⌕ SZYBKIE WYSZUKIWANIE", searchByName: "Szukaj po nazwie:", searchPlaceholder: "Czego szukasz?", location: "Lokalizacja:", selectLocation: "Wybierz lokalizację", category: "Kategoria:", selectCategory: "Wybierz kategorię", priceRange: "Zakres cen:", from: "od", to: "do", search: "Szukaj", latestReviews: "NAJNOWSZE OPINIE", newCatalogs: "NOWE KATALOGI", shops: "★  SKLEPY", home: "Strona główna", verified: "✓ Zweryfikowany", deals: "Oferty", vendorLevel: "Poziom sprzedawcy", rating: "Ocena", viewShop: "Zobacz sklep", noResults: "Brak pozycji katalogu pasujących do wyszukiwania.", demoCredit: "1 KREDYT DEMO = 1,00 $", loginTitle: "Logowanie", loginSubtitle: "Zaloguj się, aby uzyskać dostęp do katalogu.", usernameOrEmail: "NAZWA UŻYTKOWNIKA LUB E-MAIL", usernameEmailPlaceholder: "Nazwa użytkownika lub e-mail", password: "HASŁO", loginButton: "Zaloguj", loggingIn: "Logowanie…", noAccount: "Nie masz konta?", registerLink: "zarejestruj się", registerTitle: "Rejestracja", registerSubtitle: "Utwórz konto dla wersji demonstracyjnej katalogu.", displayName: "NAZWA WYŚWIETLANA", yourDisplayName: "Twoja nazwa", username: "NAZWA UŻYTKOWNIKA", usernamePlaceholder: "3–32 znaki", email: "E-MAIL", passwordPlaceholder: "Co najmniej 8 znaków", repeatPassword: "POWTÓRZ HASŁO", repeatPlaceholder: "Powtórz hasło", creatingAccount: "Tworzenie konta…", alreadyAccount: "Masz już konto?", loginLink: "zaloguj się",
  },
  it: {
    categories: "CATEGORIE", language: "LINGUA", login: "ACCEDI", register: "REGISTRATI", purchases: "I MIEI ACQUISTI", messages: "MESSAGGI", help: "AIUTO", balance: "SALDO", logout: "ESCI",
    quickSearch: "⌕ RICERCA RAPIDA", searchByName: "Cerca per nome:", searchPlaceholder: "Cosa stai cercando?", location: "Posizione:", selectLocation: "Seleziona posizione", category: "Categoria:", selectCategory: "Seleziona categoria", priceRange: "Fascia di prezzo:", from: "da", to: "a", search: "Cerca", latestReviews: "ULTIME RECENSIONI", newCatalogs: "NUOVI CATALOGHI", shops: "★  NEGOZI", home: "Home", verified: "✓ Verificato", deals: "Offerte", vendorLevel: "Livello venditore", rating: "Valutazione", viewShop: "Vedi negozio", noResults: "Nessun articolo corrisponde alla ricerca.", demoCredit: "1 CREDITO DEMO = $1,00", loginTitle: "Accedi", loginSubtitle: "Accedi per consultare il catalogo.", usernameOrEmail: "NOME UTENTE O E-MAIL", usernameEmailPlaceholder: "Nome utente o e-mail", password: "PASSWORD", loginButton: "Accedi", loggingIn: "Accesso…", noAccount: "Non hai un account?", registerLink: "registrati", registerTitle: "Registrati", registerSubtitle: "Crea un account per la demo del catalogo.", displayName: "NOME VISUALIZZATO", yourDisplayName: "Il tuo nome visualizzato", username: "NOME UTENTE", usernamePlaceholder: "3–32 caratteri", email: "E-MAIL", passwordPlaceholder: "Almeno 8 caratteri", repeatPassword: "RIPETI PASSWORD", repeatPlaceholder: "Ripeti password", creatingAccount: "Creazione account…", alreadyAccount: "Hai già un account?", loginLink: "accedi",
  },
  es: {
    categories: "CATEGORÍAS", language: "IDIOMA", login: "INICIAR SESIÓN", register: "REGISTRARSE", purchases: "MIS COMPRAS", messages: "MENSAJES", help: "AYUDA", balance: "SALDO", logout: "CERRAR SESIÓN",
    quickSearch: "⌕ BÚSQUEDA RÁPIDA", searchByName: "Buscar por nombre:", searchPlaceholder: "¿Qué estás buscando?", location: "Ubicación:", selectLocation: "Seleccionar ubicación", category: "Categoría:", selectCategory: "Seleccionar categoría", priceRange: "Rango de precio:", from: "desde", to: "hasta", search: "Buscar", latestReviews: "ÚLTIMAS RESEÑAS", newCatalogs: "NUEVOS CATÁLOGOS", shops: "★  TIENDAS", home: "Inicio", verified: "✓ Verificado", deals: "Ofertas", vendorLevel: "Nivel del vendedor", rating: "Valoración", viewShop: "Ver tienda", noResults: "Ningún artículo coincide con tu búsqueda.", demoCredit: "1 CRÉDITO DEMO = 1,00 $", loginTitle: "Iniciar sesión", loginSubtitle: "Inicia sesión para acceder al catálogo.", usernameOrEmail: "USUARIO O CORREO", usernameEmailPlaceholder: "Tu usuario o correo", password: "CONTRASEÑA", loginButton: "Iniciar sesión", loggingIn: "Iniciando sesión…", noAccount: "¿No tienes una cuenta?", registerLink: "regístrate", registerTitle: "Registrarse", registerSubtitle: "Crea una cuenta para la demostración del catálogo.", displayName: "NOMBRE VISIBLE", yourDisplayName: "Tu nombre visible", username: "USUARIO", usernamePlaceholder: "3–32 caracteres", email: "CORREO", passwordPlaceholder: "Al menos 8 caracteres", repeatPassword: "REPETIR CONTRASEÑA", repeatPlaceholder: "Repite la contraseña", creatingAccount: "Creando cuenta…", alreadyAccount: "¿Ya tienes una cuenta?", loginLink: "inicia sesión",
  },
  fr: {
    categories: "CATÉGORIES", language: "LANGUE", login: "SE CONNECTER", register: "S’INSCRIRE", purchases: "MES ACHATS", messages: "MESSAGES", help: "AIDE", balance: "SOLDE", logout: "SE DÉCONNECTER",
    quickSearch: "⌕ RECHERCHE RAPIDE", searchByName: "Rechercher par nom :", searchPlaceholder: "Que recherchez-vous ?", location: "Lieu :", selectLocation: "Sélectionner un lieu", category: "Catégorie :", selectCategory: "Sélectionner une catégorie", priceRange: "Fourchette de prix :", from: "de", to: "à", search: "Rechercher", latestReviews: "DERNIERS AVIS", newCatalogs: "NOUVEAUX CATALOGUES", shops: "★  BOUTIQUES", home: "Accueil", verified: "✓ Vérifié", deals: "Offres", vendorLevel: "Niveau vendeur", rating: "Évaluation", viewShop: "Voir la boutique", noResults: "Aucun article ne correspond à votre recherche.", demoCredit: "1 CRÉDIT DÉMO = 1,00 $", loginTitle: "Connexion", loginSubtitle: "Connectez-vous pour accéder au catalogue.", usernameOrEmail: "NOM D’UTILISATEUR OU E-MAIL", usernameEmailPlaceholder: "Votre nom d’utilisateur ou e-mail", password: "MOT DE PASSE", loginButton: "Se connecter", loggingIn: "Connexion…", noAccount: "Vous n’avez pas de compte ?", registerLink: "inscrivez-vous", registerTitle: "Inscription", registerSubtitle: "Créez un compte pour la démo du catalogue.", displayName: "NOM D’AFFICHAGE", yourDisplayName: "Votre nom d’affichage", username: "NOM D’UTILISATEUR", usernamePlaceholder: "3–32 caractères", email: "E-MAIL", passwordPlaceholder: "Au moins 8 caractères", repeatPassword: "RÉPÉTER LE MOT DE PASSE", repeatPlaceholder: "Répétez le mot de passe", creatingAccount: "Création du compte…", alreadyAccount: "Vous avez déjà un compte ?", loginLink: "connectez-vous",
  },
  pt: {
    categories: "CATEGORIAS", language: "IDIOMA", login: "ENTRAR", register: "REGISTAR", purchases: "AS MINHAS COMPRAS", messages: "MENSAGENS", help: "AJUDA", balance: "SALDO", logout: "SAIR",
    quickSearch: "⌕ PESQUISA RÁPIDA", searchByName: "Pesquisar por nome:", searchPlaceholder: "O que procura?", location: "Localização:", selectLocation: "Selecionar localização", category: "Categoria:", selectCategory: "Selecionar categoria", priceRange: "Intervalo de preço:", from: "de", to: "até", search: "Pesquisar", latestReviews: "AVALIAÇÕES RECENTES", newCatalogs: "NOVOS CATÁLOGOS", shops: "★  LOJAS", home: "Início", verified: "✓ Verificado", deals: "Ofertas", vendorLevel: "Nível do vendedor", rating: "Avaliação", viewShop: "Ver loja", noResults: "Nenhum item corresponde à sua pesquisa.", demoCredit: "1 CRÉDITO DEMO = $1,00", loginTitle: "Entrar", loginSubtitle: "Entre para aceder ao catálogo.", usernameOrEmail: "UTILIZADOR OU E-MAIL", usernameEmailPlaceholder: "O seu utilizador ou e-mail", password: "PALAVRA-PASSE", loginButton: "Entrar", loggingIn: "A entrar…", noAccount: "Não tem uma conta?", registerLink: "registe-se", registerTitle: "Registar", registerSubtitle: "Crie uma conta para a demonstração do catálogo.", displayName: "NOME DE EXIBIÇÃO", yourDisplayName: "O seu nome de exibição", username: "UTILIZADOR", usernamePlaceholder: "3–32 caracteres", email: "E-MAIL", passwordPlaceholder: "Pelo menos 8 caracteres", repeatPassword: "REPETIR PALAVRA-PASSE", repeatPlaceholder: "Repita a palavra-passe", creatingAccount: "A criar conta…", alreadyAccount: "Já tem uma conta?", loginLink: "entrar",
  },
  hr: {
    categories: "KATEGORIJE", language: "JEZIK", login: "PRIJAVA", register: "REGISTRACIJA", purchases: "MOJE KUPOVINE", messages: "PORUKE", help: "POMOĆ", balance: "STANJE", logout: "ODJAVA",
    quickSearch: "⌕ BRZA PRETRAGA", searchByName: "Pretraži po nazivu:", searchPlaceholder: "Što tražite?", location: "Lokacija:", selectLocation: "Odaberi lokaciju", category: "Kategorija:", selectCategory: "Odaberi kategoriju", priceRange: "Raspon cijene:", from: "od", to: "do", search: "Pretraži", latestReviews: "NAJNOVIJE RECENZIJE", newCatalogs: "NOVI KATALOZI", shops: "★  TRGOVINE", home: "Početna", verified: "✓ Potvrđeno", deals: "Ponude", vendorLevel: "Razina prodavatelja", rating: "Ocjena", viewShop: "Pogledaj trgovinu", noResults: "Nema stavki koje odgovaraju pretrazi.", demoCredit: "1 DEMO KREDIT = $1,00", loginTitle: "Prijava", loginSubtitle: "Prijavite se za pristup katalogu.", usernameOrEmail: "KORISNIČKO IME ILI E-MAIL", usernameEmailPlaceholder: "Korisničko ime ili e-mail", password: "LOZINKA", loginButton: "Prijava", loggingIn: "Prijava…", noAccount: "Nemate račun?", registerLink: "registrirajte se", registerTitle: "Registracija", registerSubtitle: "Izradite račun za demo kataloga.", displayName: "PRIKAZANO IME", yourDisplayName: "Vaše prikazano ime", username: "KORISNIČKO IME", usernamePlaceholder: "3–32 znaka", email: "E-MAIL", passwordPlaceholder: "Najmanje 8 znakova", repeatPassword: "PONOVITE LOZINKU", repeatPlaceholder: "Ponovite lozinku", creatingAccount: "Izrada računa…", alreadyAccount: "Već imate račun?", loginLink: "prijavite se",
  },
};
